/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/JJn3P9t9Aak
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"
import Link from "next/link"

export function Contact() {
  return (
    <div className="w-full max-w-5xl mx-auto py-12 md:py-16 lg:py-20 px-4 md:px-6 lg:px-8">
      <div className="grid grid-cols-1 md:grid-cols-2 gap-8 md:gap-12 lg:gap-16">
        <div className="space-y-6">
          <div>
            <h1 className="text-3xl md:text-4xl font-bold">Get in Touch</h1>
            <p className="text-muted-foreground mt-2">
              Have a question or need assistance? Fill out the form and we'll get back to you as soon as possible.
            </p>
          </div>
          <form className="space-y-4">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <Label htmlFor="name">Name</Label>
                <Input id="name" placeholder="Enter your name" />
              </div>
              <div>
                <Label htmlFor="email">Email</Label>
                <Input id="email" type="email" placeholder="Enter your email" />
              </div>
            </div>
            <div>
              <Label htmlFor="subject">Subject</Label>
              <Input id="subject" placeholder="Enter the subject" />
            </div>
            <div>
              <Label htmlFor="message">Message</Label>
              <Textarea id="message" rows={5} placeholder="Enter your message" />
            </div>
            <Button type="submit" className="w-full md:w-auto">
              Submit
            </Button>
          </form>
        </div>
        <div className="space-y-6">
          <div>
            <h2 className="text-2xl md:text-3xl font-bold">Contact Information</h2>
            <p className="text-muted-foreground mt-2">Get in touch with us using the information below.</p>
          </div>
          <div className="space-y-4">
            <div>
              <h3 className="text-lg font-medium">Address</h3>
              <p className="text-muted-foreground">123 Main St, Anytown USA 12345</p>
            </div>
            <div>
              <h3 className="text-lg font-medium">Phone</h3>
              <p className="text-muted-foreground">+1 (555) 555-5555</p>
            </div>
            <div>
              <h3 className="text-lg font-medium">Email</h3>
              <Link href="#" className="text-blue-600" prefetch={false}>
                info@example.com
              </Link>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
