'use client'
/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/G3fG1NovqMt
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Chivo } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select"
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { SetStateAction, useRef, useState } from "react"
import { ListOrderedIcon, Plus, X } from "lucide-react"
import { Checkbox } from "../ui/checkbox"
import { Inputfile } from "./inputfile"
import Image from "next/image"
import ImageContainer from "../functional/ImageContainer"
import { createProduct } from "@/actions/product"
import SizeSelection from "../functional/SizeSelection"
import ColorSelection from "../functional/ColorSelection"
import { productDataPosting } from "@/types/product"
import { Slider } from "@/components/ui/slider"
import toast, { Toaster } from "react-hot-toast"
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuLabel, DropdownMenuRadioGroup, DropdownMenuRadioItem, DropdownMenuSeparator, DropdownMenuTrigger } from "../ui/dropdown-menu"
import { useRouter } from "next/navigation"


interface ColorOption {
  color: string
  combination_price: number
}

export type SizersAndColorsType ={
  size:string,
  dimensions?:string,
  stockQuantity?:number,
  colors:Array<{color:string,combination_price:number}>
}

export type OtherDataType={
  name:string,description:string,category:string,price:number,stockQuantity: number,carousel:boolean,most_selling_product:boolean,isNew:boolean,product_specification:{
    material:string,
    careInstruction: string,
    // dimensions: string,
  }
  productDiscount:number,
  wholesaleDiscount:number,
  taxRate:number,
  shippingCharges:number
}

export function CreateWholesaleProduct() {
  const [images,setImages]=useState<File[]>([])
  const [otherData,setOtherData]=useState<OtherDataType>({
    name: '',
    description: '',
    category: 'WHOLESALE',
    price: 0, // Initialize with 0
    stockQuantity: 0, // Initialize with 0
    carousel: false, // Default to false (not user-selectable)
    most_selling_product: false, // Default to false (not user-selectable)
    isNew: true, // Default to true for new products
    productDiscount: 0, // Initialize with 0
    wholesaleDiscount: 10, // Default wholesale discount
    taxRate: 18, // Default tax rate
    shippingCharges: 100, // Default shipping charges
    product_specification: {
      material: '',
      careInstruction: '',
    },
  })
  const [selectedSizes, setSelectedSizes] = useState<string[]>([])
  const [selectedColors, setSelectedColors] = useState<ColorOption[]>([])
  const [isSubmiting,setIsSubmiting]=useState(false)
  const router = useRouter();

  const categories=[
    'SAREE',
    'MEN SUITING SHIRTING',
    'MEN COMBOS PACKS',
    'WOMEN STICHED SUITS',
    'WOMEN UNSTICHED SUITS',
    'LEHNGAS',
    'WOMENS OTHERS',
    'BED SHEETS',
    'CURTAINS',
    'BLANKETS',
    'MOSQUITO NETS',
    'WHOLESALE'
  ];
  
  const createNewProduct=async ()=>{

    if(!otherData.name || !otherData.price || images.length === 0){
      return toast.error('Please fill the required fields: Product Name, Price, and at least one Image.', { duration: 5000 });
    }

    // Validate numeric inputs before submission
    if (isNaN(otherData.price) || isNaN(otherData.stockQuantity) || otherData.price < 0 || otherData.stockQuantity < 0) {
      toast.error('Price and Stock Quantity must be valid positive numbers.');
      return;
    }

    toast.promise(
      new Promise(async (resolve, reject) => {
        setIsSubmiting(true);
        try {
          // Create availableSizesColors from separate size and color selections
          const availableSizesColors = selectedSizes.length > 0 
            ? selectedSizes.map(size => ({
                size,
                colors: selectedColors,
                stockQuantity: otherData.stockQuantity || 0
              }))
            : [{
                size: 'One Size',
                colors: selectedColors,
                stockQuantity: otherData.stockQuantity || 0
              }]

          const data: productDataPosting = {
            name: otherData.name,
            description: otherData.description || '',
            price: otherData.price,
            discountPercentage: 0, // No product discount for wholesale
            category: 'WHOLESALE', // Force wholesale category
            stockQuantity: otherData.stockQuantity || 0,
            availableSizesColors: JSON.stringify(availableSizesColors),
            isAvailable: true,
            product_specification: otherData.product_specification || {},
            carousel: otherData.carousel || false,
            most_selling_product: otherData.most_selling_product || false,
            isNew: otherData.isNew || false,
          };

          const formData = new FormData();
          formData.append('data', JSON.stringify(data));
          for (let file of images) {
            formData.append('images[]', file, file.name);
          }
          
          // Get token from cookie
          const token = document.cookie.split('; ').find(row => row.startsWith('token='))?.split('=')[1];
          
          const response = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/api/products`, {
            method: 'POST',
            credentials: 'include',
            headers: {
              'Authorization': `Bearer ${token}`
            },
            body: formData,
          });
          if (!response.ok) {
            throw new Error('Failed to create product');
          }
          resolve('Product created successfully!');
          // Redirect and refresh products list
          router.push('/products');
          router.refresh();
        } catch (error) {
          console.error('Error creating product:', error);
          reject('Failed to create product.');
        } finally {
          setIsSubmiting(false);
        }
      }),
      {
        loading: 'Creating product...',
        success: 'Product created successfully!',
        error: 'Failed to create product.',
      }
    );
  }

  return (
    <>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-8 w-full px-4 md:px-6 py-12">
        <div className="grid gap-6">
          <div className="grid gap-2">
            <Label htmlFor="name">Product Name *</Label>
            <Input value={otherData.name} onChange={(e)=>{setOtherData({...otherData,name:e.target.value})}} id="name" type="text" placeholder="Enter product name" />
          </div>
          <div className="grid gap-2">
            <Label htmlFor="description">Description</Label>
            <Textarea value={otherData.description} onChange={(e)=>setOtherData({...otherData,description:e.target.value})} id="description" placeholder="Enter product description" className="min-h-[120px]" />
          </div>

          {/* Category is fixed to WHOLESALE for wholesale products */}
          <div className="grid gap-2">
            <Label htmlFor="category">Category</Label>
            <Input value="WHOLESALE" disabled className="bg-gray-100" />
          </div>

          <div className="grid grid-cols-2 gap-6">
            <div className="grid gap-2">
              <Label htmlFor="price">Price *</Label>
              <Input value={otherData.price} onChange={(e)=>setOtherData({...otherData,price:Math.max(0, parseInt(e.target.value) || 0)})} id="price" type="number" placeholder="Enter price" min="0" />
            </div>
            <div className="grid gap-2">
              <Label htmlFor="quantity">Quantity</Label>
              <Input value={otherData.stockQuantity} onChange={(e)=>setOtherData({...otherData,stockQuantity:Math.max(0, parseInt(e.target.value) || 0)})} id="quantity" type="number" placeholder="Enter quantity" min="0" />
            </div>
          </div>
          <div className="grid gap-2">
            <Label>Product Specifications</Label>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 items-start">
              <div className="grid gap-2">
                <Label htmlFor="material">Material</Label>
                <Input value={otherData.product_specification.material} onChange={(e)=>setOtherData({
                  ...otherData,
                  product_specification:{...otherData.product_specification,material:e.target.value}})} id="material" type="text" placeholder="Enter material" />
              </div>

              <div className="grid gap-2">
                <Label htmlFor="care-instructions">Care Instructions</Label>
                <Textarea value={otherData.product_specification.careInstruction} onChange={(e)=>setOtherData({
                  ...otherData,
                  product_specification:{...otherData.product_specification,careInstruction:e.target.value}})} id="care-instructions" placeholder="Enter care instructions" className="min-h-[120px]" />
              </div>
              
            </div>
          </div>
          <div className="grid gap-4">
            <div className="grid gap-2">
              <Label>Available Sizes (Optional)</Label>
              <SizeSelection 
                selectedSizes={selectedSizes} 
                setSelectedSizes={setSelectedSizes}
              />
            </div>
            
            <div className="grid gap-2">
              <Label>Available Colors (Optional)</Label>
              <ColorSelection 
                selectedColors={selectedColors} 
                setSelectedColors={setSelectedColors}
              />
            </div>
          </div>
          
          {/* Marketing Options */}
          <div className="grid gap-2">
            <Label>Marketing</Label>
            <div className="grid grid-cols-1 gap-4">
              <div className="flex items-center space-x-2">
                <Checkbox 
                  id="newBadge"
                  checked={otherData.isNew}
                  onCheckedChange={(checked) => setOtherData({...otherData, isNew: !!checked})}
                />
                <Label htmlFor="newBadge">Show NEW badge on product card</Label>
              </div>
            </div>
          </div>

          {/* Wholesale Configuration */}
          <div className="grid gap-4">
            <Label>Wholesale Configuration</Label>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <div className="grid gap-2">
                <Label htmlFor="wholesale-discount">Wholesale Discount (%)</Label>
                <Input 
                  value={otherData.wholesaleDiscount} 
                  onChange={(e)=>setOtherData({...otherData,wholesaleDiscount:parseFloat(e.target.value) || 0})} 
                  id="wholesale-discount" 
                  type="number" 
                  placeholder="10" 
                  min="0" 
                  max="100" 
                  step="0.1"
                />
              </div>
              <div className="grid gap-2">
                <Label htmlFor="tax-rate">Tax Rate (%)</Label>
                <Input 
                  value={otherData.taxRate} 
                  onChange={(e)=>setOtherData({...otherData,taxRate:parseFloat(e.target.value) || 0})} 
                  id="tax-rate" 
                  type="number" 
                  placeholder="18" 
                  min="0" 
                  max="100" 
                  step="0.01"
                />
              </div>
              <div className="grid gap-2">
                <Label htmlFor="shipping-charges">Shipping Charges (₹)</Label>
                <Input 
                  value={otherData.shippingCharges} 
                  onChange={(e)=>setOtherData({...otherData,shippingCharges:parseFloat(e.target.value) || 0})} 
                  id="shipping-charges" 
                  type="number" 
                  placeholder="100" 
                  min="0" 
                  step="1"
                />
              </div>
            </div>
            <div className="bg-blue-50 border border-blue-200 rounded-lg p-3">
              <p className="text-sm text-blue-800 mb-2">
                <strong>Note:</strong> These settings will apply to all wholesale cart and checkout calculations.
              </p>
              <div className="text-sm text-blue-700">
                <strong>Live Calculation (Current Product Price: ₹{otherData.price}):</strong><br/>
                Base: ₹{otherData.price} → After Discount ({otherData.wholesaleDiscount}%): ₹{(otherData.price - (otherData.price * otherData.wholesaleDiscount / 100)).toFixed(2)} → Tax ({otherData.taxRate}%): +₹{((otherData.price - (otherData.price * otherData.wholesaleDiscount / 100)) * otherData.taxRate / 100).toFixed(2)} → Shipping: +₹{otherData.shippingCharges} = <strong className="text-green-700 text-base">Total: ₹{(otherData.price - (otherData.price * otherData.wholesaleDiscount / 100) + ((otherData.price - (otherData.price * otherData.wholesaleDiscount / 100)) * otherData.taxRate / 100) + otherData.shippingCharges).toFixed(2)}</strong>
              </div>
            </div>
          </div>
        </div>
        <div className="grid gap-6">
          <Card>
            <CardHeader>
              <CardTitle>Product Images</CardTitle>
              <CardDescription>
                Upload images for your product. <br />
                The first image should be the thumbnail of your product<br />
                <span className="text-red-600 font-medium">Maximum file size: 3MB per image</span>
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="grid gap-4">
                <div className="grid grid-cols-3 gap-2">
                  {Array(3).fill(0).map((_val,ind)=>{
                  return (
                  <button key={ind} className="flex aspect-square w-full items-center justify-center rounded-md border border-dashed">
                    <span className="sr-only">Upload</span>
                    <div className=" w-full h-full">
                      <ImageContainer ind={ind} setFiles={setImages} image={images[ind]}/>
                    </div>
                  </button>)})}
                </div>
                <div className="grid grid-cols-3 gap-2">
                  {Array(3).fill(0).map((_val,ind)=>{
                  return(
                    <button key={ind} className="flex aspect-square w-full items-center justify-center rounded-md border border-dashed">
                      <span className="sr-only">Upload</span>
                      <div className=" w-full h-full">
                          <ImageContainer ind={ind+3} setFiles={setImages} image={images[ind+3]}/>
                      </div>
                    </button>
                    )})
                  }
                </div>
              </div>
            </CardContent>
          </Card>
          <div className="flex justify-end gap-2">
            <Button variant="outline">Cancel</Button>
            <Button disabled={isSubmiting} onClick={()=>{
              createNewProduct()
            }}>Save Product</Button>
          </div>
        </div>
      </div>
    </>
  )
}
export default CreateWholesaleProduct;
