'use client'

/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/5Btlvj8iLAT
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Input } from "@/components/ui/input"

export function Inputfile({onFileChange,accept}:{onFileChange:(e:File | undefined)=>void,accept:string}) {
  return (
    <div className="w-full max-w-sm bg-background rounded-lg p-6 flex items-center justify-center">
      <div className="relative w-full aspect-square">
        <div className="absolute inset-0 flex items-center justify-center">
          <div className="bg-primary text-primary-foreground rounded-full p-3">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              strokeWidth={1.5}
              stroke="currentColor"
              className="w-6 h-6"
            >
              <path strokeLinecap="round" strokeLinejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
            </svg>
          </div>
        </div>
        <Input accept={accept} onChange={(e)=>onFileChange(e.target?.files?.[0])} id="picture" type="file" className="w-full h-full opacity-0 cursor-pointer" />
      </div>
    </div>
  )
}
