/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/ZVxlFQyLbna
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"

import { useState, useMemo, JSX, SVGProps, SetStateAction, useEffect } from "react"
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuCheckboxItem } from "@/components/ui/dropdown-menu"
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from "@/components/ui/table"
import { Badge } from "@/components/ui/badge"
import toast from "react-hot-toast"
import { Search, Eye, X } from "lucide-react"
import Image from "next/image"
import { cleanDropdownText } from "@/lib/text-utils"
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog"

export function Orders() {
  const [search, setSearch] = useState("")
  const [selectedStatus, setSelectedStatus] = useState("all")
  const [sortColumn, setSortColumn] = useState("_id")
  const [sortDirection, setSortDirection] = useState("desc")
  const [orders, setOrders] = useState<any[]>([])
  const [loading, setLoading] = useState(true)
  const [pagination, setPagination] = useState({ currentPage: 1, totalPages: 1, count: 0 })
  const [adminUpdates, setAdminUpdates] = useState<{[key: string]: {status: string, reason?: string}}>({})

  // Get auth headers
  const getAuthHeaders = () => {
    const token = document.cookie.split('; ').find(row => row.startsWith('token='))?.split('=')[1];
    return {
      'Content-Type': 'application/json',
      'Accept': 'application/json',
      ...(token && { 'Authorization': `Bearer ${token}` })
    };
  };

  useEffect(() => {
    // Load admin updates from localStorage
    const savedUpdates = localStorage.getItem('adminOrderUpdates')
    if (savedUpdates) {
      setAdminUpdates(JSON.parse(savedUpdates))
    }
    fetchOrders()
    
    // Listen for user profile updates
    const syncInterval = setInterval(() => {
      const syncData = localStorage.getItem('adminOrdersSync')
      if (syncData) {
        const { timestamp, orderId, status, reason, type } = JSON.parse(syncData)
        // Only apply if it's a recent update (within last 5 seconds) and it's regular orders
        if (Date.now() - timestamp < 5000 && type === 'regular') {
          setOrders(prev => {
            const updated = prev.map(order => {
              if (order._id === orderId) {
                return { 
                  ...order, 
                  status, 
                  cancelReason: status === 'cancelled' ? reason : order.cancelReason,
                  returnReason: status === 'returned' ? reason : order.returnReason
                }
              }
              return order
            })
            return updated
          })
          // Update admin updates as well
          const newAdminUpdates = { ...adminUpdates, [orderId]: { status, reason } }
          setAdminUpdates(newAdminUpdates)
          localStorage.setItem('adminOrderUpdates', JSON.stringify(newAdminUpdates))
          // Clear the sync data
          localStorage.removeItem('adminOrdersSync')
          toast.success(`Order ${orderId.slice(-8)} ${status} by customer`)
        }
      }
    }, 1000)
    
    return () => clearInterval(syncInterval)
  }, [])

  const fetchOrders = async () => {
    try {
      setLoading(true)
      const response = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/api/orders/all`, {
        method: 'GET',
        headers: getAuthHeaders(),
        credentials: 'include'
      })
      
      if (!response.ok) {
        throw new Error(`HTTP ${response.status}: ${response.statusText}`)
      }
      
      const orders = await response.json()
      setOrders(Array.isArray(orders) ? orders : [])
    } catch (error) {
      console.error('Error fetching orders:', error)
      toast.error('Failed to load orders')
      setOrders([])
    } finally {
      setLoading(false)
    }
  }

  const handleStatusUpdate = async (orderId: string, status: string) => {
    const apiUrl = `${process.env.NEXT_PUBLIC_API_URL}/api/orders/admin/${orderId}/status`
    console.log('Updating order status:', { orderId, status, apiUrl })
    
    try {
      const response = await fetch(apiUrl, {
        method: 'PUT',
        headers: getAuthHeaders(),
        credentials: 'include',
        body: JSON.stringify({ status, sendEmail: true })
      })
      
      console.log('Response status:', response.status, response.statusText)
      
      if (!response.ok) {
        const errorText = await response.text()
        console.error('Error response:', errorText)
        throw new Error(`HTTP ${response.status}: ${errorText}`)
      }
      
      const result = await response.json()
      console.log('Update result:', result)
      
      if (result.success) {
        // Update local state after successful API call
        setOrders(prevOrders => {
          const updatedOrders = prevOrders.map(order => 
            order._id === orderId ? { ...order, status } : order
          )
          return updatedOrders
        })
        
        // Save admin updates
        const newUpdates = { ...adminUpdates, [orderId]: { status } }
        setAdminUpdates(newUpdates)
        localStorage.setItem('adminOrderUpdates', JSON.stringify(newUpdates))
        
        // Sync with user profile
        localStorage.setItem('userOrdersSync', JSON.stringify({ 
          timestamp: Date.now(), 
          orderId, 
          status,
          type: 'regular'
        }))
        
        toast.success('Order status updated and email sent')
      } else {
        toast.error(result.message || 'Failed to update status')
      }
    } catch (error) {
      console.error('Status update error:', error)
      toast.error(`Error: ${error instanceof Error ? error.message : 'Unknown error'}`)
    }
  }

  const handleDeleteOrder = async (orderId: string) => {
    if (!confirm('Are you sure you want to delete this order?')) return
    
    try {
      const response = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/api/orders/${orderId}`, {
        method: 'DELETE',
        headers: getAuthHeaders(),
        credentials: 'include'
      })
      
      if (response.ok) {
        setOrders(prevOrders => prevOrders.filter(order => order._id !== orderId))
        
        // Sync deletion with user profile
        localStorage.setItem('adminDeleteSync', JSON.stringify({ 
          timestamp: Date.now(), 
          orderId, 
          type: 'regular',
          action: 'delete'
        }))
        
        toast.success('Order deleted successfully')
      } else {
        toast.error('Failed to delete order')
      }
    } catch (error) {
      toast.error('Error deleting order')
    }
  }
  const filteredOrders = useMemo(() => {
    let filtered = orders.filter((order) => {
      if (selectedStatus === "all") return true
      return order.status === selectedStatus
    })
    if (search) {
      filtered = filtered.filter(
        (order) =>
          order._id.toLowerCase().includes(search.toLowerCase()) ||
          (order.user?.username || '').toLowerCase().includes(search.toLowerCase()),
      )
    }
    return filtered.sort((a:any, b:any) => {
      if (a[sortColumn] < b[sortColumn]) return sortDirection === "asc" ? -1 : 1
      if (a[sortColumn] > b[sortColumn]) return sortDirection === "asc" ? 1 : -1
      return 0
    })
  }, [orders, search, selectedStatus, sortColumn, sortDirection])
  const handleSort = (column: SetStateAction<string>) => {
    if (sortColumn === column) {
      setSortDirection(sortDirection === "asc" ? "desc" : "asc")
    } else {
      setSortColumn(column)
      setSortDirection("asc")
    }
  }
  return (
    <div className="p-6 space-y-6">
      {/* Header Section */}
      <div className="bg-white border-b border-gray-200 p-6">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-2xl font-semibold text-gray-900">Orders</h1>
            <p className="text-gray-600 mt-1">Manage customer orders</p>
          </div>
          <div className="text-right">
            <div className="text-2xl font-semibold text-gray-900">{filteredOrders.length}</div>
            <div className="text-sm text-gray-500">Total Orders</div>
          </div>
        </div>
      </div>

      {/* Filters Section */}
      <div className="bg-white border-b border-gray-200 p-6">
        <div className="flex flex-col lg:flex-row items-start lg:items-center justify-between gap-4">
          <div className="flex flex-col sm:flex-row items-start sm:items-center gap-4 w-full lg:w-auto">
            <Input
              type="search"
              placeholder="Search orders..."
              className="w-full sm:w-64 lg:w-80"
              value={search}
              onChange={(e) => setSearch(e.target.value)}
            />
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button variant="outline">
                  Status Filter
                </Button>
              </DropdownMenuTrigger>
                <DropdownMenuContent align="end" className="w-48 bg-white border-gray-200">
                  <DropdownMenuLabel>Filter by status</DropdownMenuLabel>
                  <DropdownMenuSeparator />
                  <DropdownMenuCheckboxItem
                    checked={selectedStatus === "all"}
                    onCheckedChange={() => setSelectedStatus("all")}
                  >
                    All
                  </DropdownMenuCheckboxItem>
                  <DropdownMenuCheckboxItem
                    checked={selectedStatus === "pending"}
                    onCheckedChange={() => setSelectedStatus("pending")}
                  >
                    Pending
                  </DropdownMenuCheckboxItem>
                  <DropdownMenuCheckboxItem
                    checked={selectedStatus === "shipped"}
                    onCheckedChange={() => setSelectedStatus("shipped")}
                  >
                    Shipped
                  </DropdownMenuCheckboxItem>
                  <DropdownMenuCheckboxItem
                    checked={selectedStatus === "delivered"}
                    onCheckedChange={() => setSelectedStatus("delivered")}
                  >
                    Delivered
                  </DropdownMenuCheckboxItem>
                  <DropdownMenuCheckboxItem
                    checked={selectedStatus === "cancelled"}
                    onCheckedChange={() => setSelectedStatus("cancelled")}
                  >
                    Cancelled
                  </DropdownMenuCheckboxItem>
                  <DropdownMenuCheckboxItem
                    checked={selectedStatus === "returned"}
                    onCheckedChange={() => setSelectedStatus("returned")}
                  >
                    Returned
                  </DropdownMenuCheckboxItem>
                </DropdownMenuContent>
              </DropdownMenu>
          </div>
        </div>
      </div>
      
      {/* Orders Table */}
      <div className="bg-white border border-gray-200 overflow-hidden">
          <div className="overflow-x-auto">
            {loading ? (
              <div className="flex justify-center items-center h-64">
                <div className="flex flex-col items-center gap-4">
                  <div className="w-12 h-12 border-4 border-purple-200 border-t-purple-600 rounded-full animate-spin"></div>
                  <div className="text-center">
                    <p className="text-lg font-semibold text-gray-700">Loading orders...</p>
                    <p className="text-sm text-gray-500">Fetching the latest order data</p>
                  </div>
                </div>
              </div>
            ) : (
              <Table>
                <TableHeader>
                  <TableRow className="border-b border-gray-100">
                    <TableHead className="cursor-pointer font-semibold text-gray-700" onClick={() => handleSort("_id")}>
                      Order ID
                      {sortColumn === "_id" && (
                        <span className="ml-2">{sortDirection === "asc" ? "↑" : "↓"}</span>
                      )}
                    </TableHead>
                    <TableHead className="hidden md:table-cell font-semibold text-gray-700">Tracking ID</TableHead>
                    <TableHead className="hidden md:table-cell font-semibold text-gray-700">Customer</TableHead>
                    <TableHead className="hidden lg:table-cell cursor-pointer font-semibold text-gray-700" onClick={() => handleSort("createdAt")}>
                      Date
                      {sortColumn === "createdAt" && (
                        <span className="ml-2">{sortDirection === "asc" ? "↑" : "↓"}</span>
                      )}
                    </TableHead>
                    <TableHead className="cursor-pointer text-right font-semibold text-gray-700" onClick={() => handleSort("total")}>
                      Total
                      {sortColumn === "total" && (
                        <span className="ml-2">{sortDirection === "asc" ? "↑" : "↓"}</span>
                      )}
                    </TableHead>
                    <TableHead className="hidden lg:table-cell font-semibold text-gray-700">Payment</TableHead>
                    <TableHead className="font-semibold text-gray-700">Status</TableHead>
                    <TableHead className="hidden lg:table-cell font-semibold text-gray-700">Cancel/Return</TableHead>
                    <TableHead className="text-right font-semibold text-gray-700">Actions</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {filteredOrders.length > 0 ? (
                    filteredOrders.map((order) => (
                      <TableRow key={order._id} className="hover:bg-gray-50/50 transition-colors">
                        <TableCell>
                          <span className="font-mono text-sm text-gray-900">
                            #{order._id.slice(-8)}
                          </span>
                        </TableCell>
                        <TableCell className="hidden md:table-cell">
                          <button 
                            onClick={() => {
                              const productLinks = order.products.map((item: any) => 
                                `https://royaldgmart.com/product-view/${item.product?._id}`
                              ).join('\n');
                              
                              // Open each product in a new tab
                              order.products.forEach((item: any) => {
                                if (item.product?._id) {
                                  window.open(`https://royaldgmart.com/product-view/${item.product._id}`, '_blank');
                                }
                              });
                            }}
                            className="font-mono text-xs text-blue-600 hover:text-blue-800 underline cursor-pointer"
                            title="Click to view ordered products"
                          >
                            {order._id}
                          </button>
                        </TableCell>
                        <TableCell className="hidden md:table-cell">
                          <div>
                            <div className="font-medium text-gray-900">{order.shippingDetails?.firstName} {order.shippingDetails?.lastName}</div>
                            <div className="text-sm text-gray-500">{order.shippingDetails?.email}</div>
                          </div>
                        </TableCell>
                        <TableCell className="hidden lg:table-cell text-gray-600 text-sm">{new Date(order.createdAt).toLocaleDateString()}</TableCell>
                        <TableCell className="text-right">
                          <div className="font-semibold text-gray-900">
                            ₹{order.total?.toFixed(2) || '0.00'}
                          </div>
                        </TableCell>
                        <TableCell className="hidden lg:table-cell">
                          <div className="space-y-1">
                            <div className="text-sm font-medium text-gray-900">
                              {order.paymentMethod === 'cod' ? 'COD' :
                               order.paymentMethod === 'razorpay' ? 'Razorpay' : 'Unknown'}
                            </div>
                            <div className="text-xs text-gray-500">
                              {order.paymentStatus === 'completed' ? 'Paid' :
                               order.paymentStatus === 'pending' ? 'Pending' :
                               order.paymentStatus === 'failed' ? 'Failed' : 'Unknown'}
                            </div>
                          </div>
                        </TableCell>
                        <TableCell>
                          <span className={`inline-flex px-2 py-1 text-xs font-medium rounded ${
                            order.status === 'pending' ? 'bg-yellow-100 text-yellow-800' :
                            order.status === 'confirmed' ? 'bg-blue-100 text-blue-800' :
                            order.status === 'shipped' ? 'bg-purple-100 text-purple-800' :
                            order.status === 'delivered' ? 'bg-green-100 text-green-800' :
                            order.status === 'cancelled' ? 'bg-red-100 text-red-800' :
                            order.status === 'returned' ? 'bg-orange-100 text-orange-800' :
                            order.status === 'return_approved' ? 'bg-green-100 text-green-800' :
                            order.status === 'return_initiated' ? 'bg-blue-100 text-blue-800' :
                            order.status === 'rejected' ? 'bg-red-100 text-red-800' :
                            'bg-gray-100 text-gray-800'
                          }`}>
                            {order.status === 'return_initiated' ? 'Return Initiated' :
                             order.status === 'return_approved' ? 'Return Approved' :
                             order.status.charAt(0).toUpperCase() + order.status.slice(1)}
                          </span>
                        </TableCell>
                        <TableCell className="hidden lg:table-cell">
                          {order.cancelReason && (
                            <div className="text-xs space-y-2">
                              <div className="font-medium text-red-600">Cancel Request</div>
                              <div className="text-gray-500 truncate max-w-24" title={order.cancelReason}>
                                {order.cancelReason}
                              </div>
                              {order.status !== 'cancelled' && (
                                <div className="flex flex-col gap-1">
                                  <Button size="sm" className="h-6 px-2 text-xs bg-red-600 hover:bg-red-700" onClick={() => handleStatusUpdate(order._id, 'cancelled')}>
                                    Approve
                                  </Button>
                                  <Button size="sm" variant="outline" className="h-6 px-2 text-xs" onClick={() => {
                                    const updatedOrders = orders.map(o => o._id === order._id ? {...o, cancelReason: null} : o)
                                    setOrders(updatedOrders)
                                    toast.success('Cancel request rejected')
                                  }}>
                                    Reject
                                  </Button>
                                </div>
                              )}
                            </div>
                          )}
                          {(order.returnReason || order.status === 'return_initiated') && (
                            <div className="text-xs space-y-2">
                              <Dialog>
                                <DialogTrigger asChild>
                                  <button className="font-medium text-orange-600 hover:text-orange-800 underline cursor-pointer">
                                    Return Request
                                  </button>
                                </DialogTrigger>
                                <DialogContent>
                                  <DialogHeader>
                                    <DialogTitle>Return Request Details</DialogTitle>
                                  </DialogHeader>
                                  <div className="space-y-4">
                                    <div>
                                      <p className="font-medium text-gray-900">Order ID: #{order._id.slice(-8)}</p>
                                      <p className="text-sm text-gray-600">Customer: {order.shippingDetails?.firstName} {order.shippingDetails?.lastName}</p>
                                    </div>
                                    <div>
                                      <p className="font-medium text-gray-900 mb-2">Return Reason:</p>
                                      <p className="text-sm text-gray-700 bg-gray-50 p-3 rounded border">
                                        {order.returnReason || 'Return requested without specific reason'}
                                      </p>
                                    </div>
                                  </div>
                                </DialogContent>
                              </Dialog>
                              {order.status === 'return_initiated' ? (
                                <div className="flex flex-col gap-1">
                                  <Button size="sm" className="h-6 px-2 text-xs bg-green-600 hover:bg-green-700" onClick={() => handleStatusUpdate(order._id, 'return_approved')}>
                                    Approve
                                  </Button>
                                  <Button size="sm" variant="outline" className="h-6 px-2 text-xs" onClick={() => {
                                    const updatedOrders = orders.map(o => o._id === order._id ? {...o, returnReason: null, status: 'confirmed'} : o)
                                    setOrders(updatedOrders)
                                    toast.success('Return request rejected')
                                  }}>
                                    Reject
                                  </Button>
                                </div>
                              ) : order.status !== 'returned' && order.status !== 'return_approved' && (
                                <div className="flex flex-col gap-1">
                                  <Button size="sm" className="h-6 px-2 text-xs bg-orange-600 hover:bg-orange-700" onClick={() => handleStatusUpdate(order._id, 'returned')}>
                                    Complete
                                  </Button>
                                </div>
                              )}
                            </div>
                          )}
                          {!order.cancelReason && !order.returnReason && order.status !== 'return_initiated' && (
                            <span className="text-xs text-gray-400">-</span>
                          )}
                        </TableCell>
                        <TableCell className="text-right">
                          <div className="flex flex-col sm:flex-row gap-1 sm:gap-2 justify-end">
                            <DropdownMenu>
                              <DropdownMenuTrigger asChild>
                                <Button variant="outline" size="sm" className="text-xs">
                                  Update Status
                                </Button>
                              </DropdownMenuTrigger>
                              <DropdownMenuContent>
                                <DropdownMenuLabel>Update Status</DropdownMenuLabel>
                                <DropdownMenuSeparator />
                                <DropdownMenuCheckboxItem onClick={() => handleStatusUpdate(order._id, 'pending')}>Pending</DropdownMenuCheckboxItem>
                                <DropdownMenuCheckboxItem onClick={() => handleStatusUpdate(order._id, 'confirmed')}>Confirmed</DropdownMenuCheckboxItem>
                                <DropdownMenuCheckboxItem onClick={() => handleStatusUpdate(order._id, 'shipped')}>Shipped</DropdownMenuCheckboxItem>
                                <DropdownMenuCheckboxItem onClick={() => handleStatusUpdate(order._id, 'delivered')}>Delivered</DropdownMenuCheckboxItem>
                                <DropdownMenuCheckboxItem onClick={() => handleStatusUpdate(order._id, 'return_approved')}>Return Approved</DropdownMenuCheckboxItem>
                                <DropdownMenuCheckboxItem onClick={() => handleStatusUpdate(order._id, 'return_initiated')}>Return Initiated</DropdownMenuCheckboxItem>
                                <DropdownMenuCheckboxItem onClick={() => handleStatusUpdate(order._id, 'rejected')}>Rejected</DropdownMenuCheckboxItem>
                              </DropdownMenuContent>
                            </DropdownMenu>
                            <Button variant="destructive" size="sm" onClick={() => handleDeleteOrder(order._id)} className="text-xs">
                              Delete
                            </Button>
                          </div>
                        </TableCell>
                      </TableRow>
                    ))
                  ) : (
                    <TableRow>
                      <TableCell colSpan={8} className="text-center py-12">
                        <p className="text-gray-500">No orders found</p>
                      </TableCell>
                    </TableRow>
                  )}
                </TableBody>
              </Table>
            )}
        </div>
      </div>
    </div>
  )
}

function FilterIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="22 3 2 3 10 12.46 10 19 14 21 14 12.46 22 3" />
    </svg>
  )
}


function HomeIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
      <polyline points="9 22 9 12 15 12 15 22" />
    </svg>
  )
}


function LineChartIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 3v18h18" />
      <path d="m19 9-5 5-4-4-3 3" />
    </svg>
  )
}


function Package2Icon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 9h18v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V9Z" />
      <path d="m3 9 2.45-4.9A2 2 0 0 1 7.24 3h9.52a2 2 0 0 1 1.8 1.1L21 9" />
      <path d="M12 3v6" />
    </svg>
  )
}


function PackageIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m7.5 4.27 9 5.15" />
      <path d="M21 8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16Z" />
      <path d="m3.3 7 8.7 5 8.7-5" />
      <path d="M12 22V12" />
    </svg>
  )
}


function ShoppingCartIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="8" cy="21" r="1" />
      <circle cx="19" cy="21" r="1" />
      <path d="M2.05 2.05h2l2.66 12.42a2 2 0 0 0 2 1.58h9.78a2 2 0 0 0 1.95-1.57l1.65-7.43H5.12" />
    </svg>
  )
}


function UsersIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
      <circle cx="9" cy="7" r="4" />
      <path d="M22 21v-2a4 4 0 0 0-3-3.87" />
      <path d="M16 3.13a4 4 0 0 1 0 7.75" />
    </svg>
  )
}


function XIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}