/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/RvnNAC46L39
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { getProductById } from "@/actions/product"
import { getUserData } from "@/actions/auth"
import RelatedProducts from "../functional/RelatedProducts"
import { ProductViewClient } from "./productview-client"
import { productData } from "@/types/product"
import ImagePreviwer from "../functional/ImagePreviwer"
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card"
import ProductReviews from "./product-reviews"
import { JSX, SVGProps } from "react"

interface ProductviewProps {
  productId: string
  category: string
}

export async function Productview({productId, category}: ProductviewProps) {
  const product: productData = await getProductById({id: productId})
  const user = await getUserData()

  if(!product){
      return null
  }

  // Use the category from the product data if not provided in URL
  const productCategory = category || (product as any).category || 'electronics'

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-50 to-white">
      {/* Mobile-First Hero Section */}
      <div className="max-w-7xl mx-auto px-3 sm:px-4 py-4 sm:py-8">
        <div className="grid lg:grid-cols-2 gap-6 lg:gap-12 items-start">
          {/* Image Section */}
          <div className="relative order-1">
            <div className="lg:sticky lg:top-8">
              <ImagePreviwer images={product.images}/>
            </div>
          </div>

          {/* Product Info Section */}
          <div className="space-y-4 sm:space-y-6 lg:space-y-8 order-2">
            {/* Header */}
            <div className="space-y-3 sm:space-y-4 lg:space-y-6">
              <div className="space-y-1 sm:space-y-2">
                <p className="text-xs sm:text-sm font-medium text-gray-500 uppercase tracking-wider">
                  {(product as any).category || 'Fashion'}
                </p>
                <h1 className="text-2xl sm:text-3xl lg:text-4xl xl:text-5xl font-light text-gray-900 leading-tight">
                  {product.name}
                </h1>
              </div>
              
              {/* Rating & Price Section */}
              <div className="space-y-4">
                <div className="flex items-center gap-2 sm:gap-3">
                  <div className="flex items-center">
                    <StarIcon className="w-4 h-4 sm:w-5 sm:h-5 fill-amber-400 text-amber-400" />
                    <StarIcon className="w-4 h-4 sm:w-5 sm:h-5 fill-amber-400 text-amber-400" />
                    <StarIcon className="w-4 h-4 sm:w-5 sm:h-5 fill-amber-400 text-amber-400" />
                    <StarIcon className="w-4 h-4 sm:w-5 sm:h-5 fill-amber-400 text-amber-400" />
                    <StarIcon className="w-4 h-4 sm:w-5 sm:h-5 fill-gray-200 text-gray-200" />
                  </div>
                  <span className="text-xs sm:text-sm text-gray-600">(4.2)</span>
                </div>
                <div>
                  <div className="text-2xl sm:text-3xl font-light text-gray-900">₹{product.price}</div>
                  <p className="text-xs sm:text-sm text-gray-500">Inclusive of all taxes</p>
                </div>
              </div>
            </div>

            {/* Description */}
            <div className="prose prose-gray max-w-none">
              <p className="text-gray-700 leading-relaxed text-sm sm:text-base lg:text-lg">
                {product.description}
              </p>
            </div>

            {/* Product Actions - Mobile Optimized */}
            <div className="bg-white rounded-xl sm:rounded-2xl p-4 sm:p-6 shadow-sm border border-gray-100">
              <ProductViewClient product={product} productId={productId} user={user} />
            </div>
          </div>
        </div>
      </div>
      
      {/* Content Sections - Mobile Optimized */}
      <div className="max-w-7xl mx-auto px-3 sm:px-4 space-y-8 sm:space-y-12 lg:space-y-16">
        {/* Product Specifications */}
        <section className="bg-white rounded-2xl sm:rounded-3xl p-4 sm:p-6 lg:p-8 shadow-sm border border-gray-100">
          <h2 className="text-xl sm:text-2xl font-light text-gray-900 mb-4 sm:mb-6 lg:mb-8">Product Details</h2>
          <div className="grid gap-4 sm:gap-6 md:grid-cols-3 lg:gap-8">
            <div className="space-y-1 sm:space-y-2">
              <h3 className="font-medium text-gray-900 text-sm sm:text-base">Material</h3>
              <p className="text-gray-600 text-sm sm:text-base">{product.product_specification?.material || "Premium quality fabric"}</p>
            </div>
            <div className="space-y-1 sm:space-y-2">
              <h3 className="font-medium text-gray-900 text-sm sm:text-base">Care Instructions</h3>
              <p className="text-gray-600 text-sm sm:text-base">{product.product_specification?.careInstruction || "Dry clean recommended"}</p>
            </div>
            <div className="space-y-1 sm:space-y-2">
              <h3 className="font-medium text-gray-900 text-sm sm:text-base">Dimensions</h3>
              <p className="text-gray-600 text-sm sm:text-base">{product.product_specification?.dimensions || "Standard sizing"}</p>
            </div>
          </div>
        </section>
        
        {/* Customer Reviews */}
        <section>
          <ProductReviews productId={productId} />
        </section>
        
        {/* Related Products */}
        <section>
          <RelatedProducts category={productCategory} _id={productId} />
        </section>
      </div>
    </div>
  )
}

function StarIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
    return (
      <svg
        {...props}
        xmlns="http://www.w3.org/2000/svg"
        width="24"
        height="24"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
      >
        <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
      </svg>
    )
  }
